### ISSUE TITLE
after downloading 1 video gets error

### ISSUE THREAD

**Issue by IlBudda** [merwin-asm/Ytmaker#1]
Authentication successful.

  [+] DOWNLOADING VIDEOs 
  [+] LOGGED IN TO INSTAGRAM[\green]
  [+] MAKING VIDEO 
Traceback (most recent call last):
  File "/home/gm/Ytmaker/main.py", line 155, in <module>
    make_video(files)
  File "/home/gm/Ytmaker/main.py", line 118, in make_video
    concatenate(clips,f"videos/vid_{VID_NUM}.mp4")
  File "/home/gm/Ytmaker/main.py", line 127, in concatenate
    clips = [VideoFileClip(c) for c in video_clip_paths]
  File "/home/gm/Ytmaker/main.py", line 127, in <listcomp>
    clips = [VideoFileClip(c) for c in video_clip_paths]
  File "/home/gm/.local/lib/python3.10/site-packages/moviepy/video/io/VideoFileClip.py", line 88, in __init__
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
  File "/home/gm/.local/lib/python3.10/site-packages/moviepy/video/io/ffmpeg_reader.py", line 35, in __init__
    infos = ffmpeg_parse_infos(filename, print_infos, check_duration,
  File "/home/gm/.local/lib/python3.10/site-packages/moviepy/video/io/ffmpeg_reader.py", line 270, in ffmpeg_parse_infos
    raise IOError(("MoviePy error: the file %s could not be found!\n"
OSError: MoviePy error: the file intro.mp4 could not be found!
Please check that you entered the correct path.

**Comment by IlBudda** [comment]
ok there was missing the intro.mp4 and the "videos" folder and now it works.

if i comment out the intro and the upload section the script still works?
